# Generated by Django 4.1.3 on 2022-12-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_auth', '0002_customuser_is_admin_customuser_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='clients_auth.company'),
        ),
    ]
