# Generated by Django 4.1.3 on 2022-11-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date_time_next_contact',
            field=models.DateTimeField(null=True),
        ),
    ]
